#:schema node_modules/wrangler/config-schema.json
name = "my-sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4b46c2e3ae0045a29369bd3276519f22" }
]

[assets]
directory = "./public"
